module.exports = {
	name: 'ready', //EL NOMBRE DEL EVENTO ES MUY IMPORTANTE, TIENE QUE SER EXACTAMENTE IGUAL QUE EL EVENTO ORIGINAL, LO QUE NO IMPORTA ES EL NOMBRE DEL ARCHIVO POR LO QUE PUEDES PONERLE POR EJEMPLO LISTO.JS
	once: true, //ESTE EVENTO SERA ONCE PORQUE SOLO SE EJECUTARA UNA VEZ
	async execute(client) { //EN ESTE CASO SOLO IMPORTAREMOS CLIENT PERO PUEDES IMPORTAR MAS COSAS
		console.log('Listo!')
	},
};

